### PR TITLE
Fix for #2658

### PR DESCRIPTION
**Pull request by konstantinzolotarev**

### CODE REVIEW

**Comment by konstantinzolotarev** [comment]
@mikermcneil @loicsaintroch Please take a look.

**Comment by tjwebb** [comment]
@konstantinzolotarev can you include a unit test that tests this issue?

**Comment by konstantinzolotarev** [comment]
Tests already there.

**Comment by sgress454** [comment]
Thanks @konstantinzolotarev

**Comment by tjwebb** [comment]
Thanks @konstantinzolotarev !

**Comment by Bludwarf** [comment]
Thanks @konstantinzolotarev your fix works like a charm

**Comment by BeMxself** [comment]
This bug appeared again

**Pull request merged**
