### PR TITLE
don't send stack track back for body parse errors when environment is production

### PR DESCRIPTION
**Pull request by nwhatt**
Not sure what if any tests should be updated for this.

### CODE REVIEW

**Comment by sgress454** [comment]
Thanks @nwhatt!

**Comment by RWOverdijk** [comment]
You're on fire @sgress454 :) One thing to note, shouldn't it move down 2 lines? Now the error doesn't get logged either.

**Comment by sgress454** [comment]
Ah, good call.  I thought that was consistent with what we were doing in responses, but looks like we're logging the error there even in production (which makes sense).

**Comment by RWOverdijk** [comment]
:) Still on fire though!

**Pull request merged**
