### PR TITLE
Look for custom grunt task file based on environment

### PR DESCRIPTION
**Pull request by jlphelps**
In response to #2447, use a custom grunt task list based on NODE_ENV.  User simply needs to create a corresponding file name in tasks/register/.

### CODE REVIEW

**Comment by mikermcneil** [comment]
Thanks for looking into this, @jlphelps.  I left one correction inline- if you can make that change, it's pretty much ready to merge.  The only other thing I'd ask is that you make a note about this in the relevant parts of the docs:
+ https://github.com/balderdashy/sails-docs/blob/master/concepts/Assets/TaskAutomation.md
+ https://github.com/balderdashy/sails-docs/blob/master/anatomy/myApp/tasks/register/register.md
+ https://github.com/balderdashy/sails-docs/blob/master/anatomy/myApp/tasks/register/default.js.md
+ https://github.com/balderdashy/sails-docs/blob/master/anatomy/myApp/tasks/register/prod.js.md

and in the comments of the generated Gruntfile:
+ https://github.com/balderdashy/sails-generate-gruntfile/blob/master/templates/Gruntfile.js

**Comment by jlphelps** [comment]
Thanks for the suggestion, @mikermcneil.  I have made the change you requested and created PRs for the documentation updates, in the same order you listed above.

* https://github.com/balderdashy/sails-docs/pull/456
* https://github.com/balderdashy/sails-docs/pull/453
* https://github.com/balderdashy/sails-docs/pull/454
* https://github.com/balderdashy/sails-docs/pull/455
* https://github.com/balderdashy/sails-generate-gruntfile/pull/6

Please let me know if you would like to see more/different information included in the documentation; I am happy to make changes.

**Comment by schematical** [comment]
You guys know this is in the live docs? http://sailsjs.org/documentation/anatomy/my-app/tasks/register/prod-js
You might want to move that out of the docs until this feature gets merged in or people may spend hours tearing their hair out like I just have.

**Comment by mikermcneil** [comment]
@schematical sorry about that!  Will take care of it.

**Comment by mikermcneil** [comment]
@jlphelps just a heads up:  rolled this back temporarily to allow some time to figure out what's going on with Travis and the docs situation.

**Comment by mikermcneil** [comment]
@jlphelps ok sorry about that! There was an unfortunate coincidence in that a jsinspect dependency changed at the same time as your PR got merged, causing the tests to break (but had nothing to do with your code- it's aok).

We'll pull your new docs out temporarily later today while we change the automated deployment of the Sails website to use a tag (or worst case a branch like we used to do it) then bring them back on master once we've got that set up.

Thanks again!

**Pull request merged**
