### PR TITLE
[proposal] Run test suite on node v6

### PR DESCRIPTION
**Pull request by jamesjwarren**
Would be nice to support the latest version of node - v6.

### CODE REVIEW

**Comment by mikermcneil** [comment]
@jamesjwarren down!  Looks like they're passing for Node v6.  But annoyingly enough, it seems like there has been some kind of new timing issue introduced in the tests re: Node v5.  Looking into it.

**Comment by mikermcneil** [comment]
Also need to check out: 
image
(from https://travis-ci.org/balderdashy/sails/jobs/125298732)

**Comment by mikermcneil** [comment]
And:

image


(from https://travis-ci.org/balderdashy/sails/jobs/127330842)

**Comment by mikermcneil** [comment]
+ Build history: https://travis-ci.org/balderdashy/sails/builds
+ History of recent changes to the app dir (including `.lower()`): https://github.com/balderdashy/sails/commits/master/lib/app
+ History of recent changes to tests: https://github.com/balderdashy/sails/commits/master/test

(It's also always possible that these failing tests could also just be due to race conditions that hadn't surfaced until recently.)

If anyone has time to help diagnose, I'd really appreciate it!

**Comment by mikermcneil** [comment]
@jamesjwarren thanks!

**Comment by jamesjwarren** [comment]
@mikermcneil thanks for taking a look 👍

**Pull request merged**
