### PR TITLE
Layout support for Ractive templates

### PR DESCRIPTION
**Pull request by sleewoo**
Basically rendering a layout with given string as `body` partial.

If no layout defined in `config/views.js`, `{{> body}}` used for layout.
Also ad hoc layouts allowed: `res.view(layout: 'some-layout')`

Layout is read from fs and cache used on production.

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Thank you for your pull request @sleewoo. Can you also update `configure.js` with better logs and `layoutshim.js` only if necessary please?

**Comment by sleewoo** [comment]
@loicsaintroch, updated `configure.js`
There are no loadtime setups for ractive layouts for now, so no need to update `layoutshim.js`.

**Comment by loicsaintroch** [comment]
Thank you @sleewoo

**Comment by sleewoo** [comment]
happy to contribute. Sails is amazing. inspired me a lot.

**Pull request merged**
