### PR TITLE
Update ROADMAP.md

### PR DESCRIPTION
**Pull request by Kikobeats**
related with #2612

### CODE REVIEW

**Comment by sgress454** [comment]
Come to think of it, don't we already do this?  I guess there's a lot of stuff in the `verbose` and `silly` output (by definition) so it can be hard to absorb it all, but you do get:

```
verbose: moduleloader hook loaded successfully.
verbose: userconfig hook loaded successfully.
verbose: userhooks hook loaded successfully.
verbose: logger hook loaded successfully.
verbose: request hook loaded successfully.
verbose: blueprints hook loaded successfully.
verbose: responses hook loaded successfully.
verbose: controllers hook loaded successfully.
verbose: Loading policy modules from app...
verbose: policies hook loaded successfully.
verbose: services hook loaded successfully.
verbose: csrf hook loaded successfully.
verbose: cors hook loaded successfully.
```
et cetera; just not in order.

Were you looking for more of a summary?

**Comment by Kikobeats** [comment]
hmm is true, but the verbose print also the hooks?

**Comment by sgress454** [comment]
What I posted was the output from `sails lift --verbose`.  It lists all the hooks that load.  It's just lumped in with a bunch of other logs.

**Comment by Kikobeats** [comment]
then I close the pull!

**Pull request closed without merging**
