### PR TITLE
Update async dependency

### PR DESCRIPTION
**Pull request by andyhu**
The version included in sails is too old, it lacks some functionality like `async.retry` etc.

### CODE REVIEW

**Comment by boogerlad** [comment]
This build has failed because https://github.com/caolan/async/issues/695

**Comment by andyhu** [comment]
@boogerlad Thanks for the info. I changed the dependency to v0.9.0 and it passed the test.
async and lodash are exposed as a global variable so I think it's necessary to provide developers with up to date library, otherwise sometimes it's a bit annoying that something will break just because the library is too old and not consistent with the current documentation

**Comment by mikermcneil** [comment]
@boogerlad thanks for the catch

> it's a bit confusing that something will break just because the library is too old and not consistent with the current documentation

@andyhu agreed!  The `async` and `_` globals are really just there for convenience but it is absolutely pretty weird if they are tangibly different.  Thanks for sending this :+1:

**Comment by mikermcneil** [comment]
@andyhu would you mind taking responsibility for keeping an eye on the async dep for the project in the future?  (also feel free to hit me up at [@mikermcneil](http://twitter.com/mikermcneil) as well if I miss your pr next time)

**Comment by andyhu** [comment]
@mikermcneil Sure, will do that with pleasure :)

**Pull request merged**
