### PR TITLE
Server sources watcher.

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by dangreen** [comment]
test fails because of
```
sails(master)$ node /Users/dangreen/github/sails/bin/sails.js new testApp
error: No generator called `new` found; perhaps you meant `sails generate api new`?
```

**Comment by sgress454** [comment]
HI @dangreen, thanks for posting.  Without more explanation, it's kind of hard to tell what your code is supposed to do, but assuming this is a new feature and not a bug fix, we'd need more info before we would consider merging it.  Please review our [updated contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md), then submit a proposal explaining your use case and how this approach would solve it, as well as much of a spec as you have time for? Beyond the other reasons discussed in our new contribution guide, one of the most important things about understanding your use case is so that we can ensure this is appropriately documented and tested now, and maintained properly in the future.

Thanks again for taking the time to help improve Sails!

**Comment by dangreen** [comment]
@sgress454 This feature adds to sails the sources (`"api/**/*.js", "config/**/*.js", "tasks/**/*.js"`) watcher. When these files are changed, to apply changes, sails app will be restarted.

Example:
`bootstrap.js`:
```
module.exports.bootstrap = function(cb) {
	cb();
};
```

```
jam-server(react*)$ sails lift

info: Starting app...

(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Users/dangreen/github/jam-editor/jam-server`
info: To see your app, visit http://jam.dev
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Thu Jan 21 2016 12:36:42 GMT+0600 (NOVT)

debug: Environment : development
debug: Host        : jam.dev
debug: Port        : 1337
debug: --------------------------------------------------------
```

Edit `bootstrap.js`:
```
module.exports.bootstrap = function(cb) {
	console.log("hello!");
	cb();
};
```

```
jam-server(react*)$ sails lift

info: Starting app...

(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Users/dangreen/github/jam-editor/jam-server`
info: To see your app, visit http://jam.dev
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Thu Jan 21 2016 12:36:42 GMT+0600 (NOVT)

debug: Environment : development
debug: Host        : jam.dev
debug: Port        : 1337
debug: --------------------------------------------------------

info: Restarting app...

(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
hello!
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Users/dangreen/github/jam-editor/jam-server`
info: To see your app, visit http://jam.dev
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Thu Jan 21 2016 12:43:41 GMT+0600 (NOVT)

debug: Environment : development
debug: Host        : jam.dev
debug: Port        : 1337
debug: --------------------------------------------------------
```

**Comment by dangreen** [comment]
@sgress454 ... https://github.com/sgress454/sails-hook-autoreload

**Pull request closed without merging**
