### PR TITLE
i18n module is updated

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by sgress454** [comment]
From #3611:
> i18n 0.7.0 (and the new 0.8.0) causes the Sails tests to fail. That's pretty disturbing.
>
> 0.6.0 seems to work alright, but I'm holding off for the moment. It's possible that the tests failing with 0.7.0 is due to an issue in Sails core, not in i18n; either way, someone needs a patch.

**Comment by dangreen** [comment]
@sgress454 okay, i want fix it. 
Tests fails with this error ?
```
  1 failing

  1) API and adapter generators "before all" hook:
     Uncaught Error: ENOENT: no such file or directory, uv_chdir
      at Error (native)
      at process.chdir (node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:14:9)
      at test/integration/generate.test.js:29:15
      at ChildProcess.exithandler (child_process.js:204:7)
      at maybeClose (internal/child_process.js:821:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at Pipe._onclose (net.js:469:12)
```

**Comment by dangreen** [comment]
@sgress454 can you say exact tests which fails with `i18n@0.8.0`?

**Comment by sgress454** [comment]
@dangreen You can see [the failing tests on Travis](https://travis-ci.org/balderdashy/sails/builds/113135576); they fail the same way for me locally.

**Comment by dangreen** [comment]
@sgress454 https://github.com/mashpie/i18n-node/pull/218

**Comment by mashpie** [comment]
merged - about to release as hotfix 0.8.1

**Comment by mashpie** [comment]
ok released to npm - I was thinking of adding sails to QA... time to do so :)

**Comment by dangreen** [comment]
@mashpie Thank you for very useful lib!)

**Comment by mashpie** [comment]
Thank you for patching :)

**Comment by dangreen** [comment]
@sgress454 what about merge ?

**Comment by sgress454** [comment]
Thanks for staying on top of this, I'll check it out ASAP!

**Comment by dangreen** [comment]
@sgress454 ?

**Comment by sgress454** [comment]
Thanks @dangreen!

**Pull request merged**
