### PR TITLE
Assets folder is now customizable through the sailsrc file.

### PR DESCRIPTION
**Pull request by Globegitter**
That would be the most simple implementation of what I mentioned in https://github.com/balderdashy/sails/pull/2206

This would not allow folder names such as `false`.

Any thoughts?

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Hi @Globegitter. I like the idea because it could be useful in certain cases. However it's kind of tricky to do that using `rc` and the `.sailsrc` file. For example, I never use the `.sailsrc` because I don't want/need it. I'm probably not the only one.

This customization is good but could be better as a basic configuration without using the `.sailsrc` file.

**Comment by Globegitter** [comment]
Hi @loicsaintroch so you would prefer having a setting in one of the `/config` files? @mikermcneil @sgress454 any thoughts?

This would really help us keeping the grunt hook disabled but still serving the ember app via `sails lift`.

**Comment by sgress454** [comment]
I might be misunderstanding your intent, but you can already change the assets folder location using regular configuration files or .sailsrc, by setting `paths.public`...

**Comment by Globegitter** [comment]
Aahh that is almost what I thought and might be all I need. I'll try it out and get back asap.

**Comment by Globegitter** [comment]
Oh yeah this already works with:
```js
{ 
  "hooks": { 
    "grunt": false 
  },
  "paths": {
    "public": "assets"
  }
}
```

Just does not seem to be documented. Will try to do asap.

**Pull request closed without merging**
