### PR TITLE
[implements #2676] added typescript support

### PR DESCRIPTION
**Pull request by ulucs**
Added ts-node for typescript support without compilation by adding ts-node to moduleloader

### CODE REVIEW

**Comment by justingosan** [comment]
Hi!

Is there anything else to do aside from http://sailsjs.com/documentation/tutorials/using-type-script?
My models written with *.ts don't seem to compile. I'm currently running the server through `app.js` as instructed. Using sails 0.12.13

**Comment by ulucs** [comment]
The documentation page http://sailsjs.com/documentation/tutorials/using-type-script is for version 1.0. Typescript won't work on 0.12 unless this or some other workaround gets merged

**Comment by justingosan** [comment]
I see. thanks for the heads up

Justin

On Wed, 19 Apr 2017 at 12:39 AM ulucs

<
mailto:ulucs <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

The documentation page
http://sailsjs.com/documentation/tutorials/using-type-script
is for version 1.0. Typescript won't work on 0.12 unless this or some other workaround gets merged

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/balderdashy/sails/pull/4044#issuecomment-294904428
, or

**Comment by sgress454** [comment]
> The documentation page http://sailsjs.com/documentation/tutorials/using-type-script
is for version 1.0. Typescript won't work on 0.12 unless this or some other workaround gets merged

The documentation has been fixed for 0.12; it should work now without any changes to Sails.

**Pull request closed without merging**
