### PR TITLE
[proposal] Add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by mikermcneil** [comment]
@DanielRuf Thanks!  Any idea what's up with mocha in node 10 on windows?

**Comment by DanielRuf** [comment]
I'll try to resolve ot today or this weekend at home (have Windows 10 there so I can test). Possibly just a dependency.

**Comment by DanielRuf** [comment]
Also failing unit tests at https://github.com/sailshq/machinepack-process

**Comment by mikermcneil** [comment]
> I do not get these errors on my Windows 10 laptop (where the tests also run faster).

good to know

**Comment by DanielRuf** [comment]
Already applied a while ago so I will close this PR.

**Pull request closed without merging**
