### PR TITLE
[patch] Corrected the way to actually pass the files to evaluate during eslinting

### PR DESCRIPTION
**Pull request by luislobo**
It specifies the exact folders, and the globbing works on more files, raising the issues to a lot more, unfortunately (or fortunatelly??)

Also, as specific folders are set, node_modules are not evaluated, and it does fail like it fails in Travis, trying to lint node_modules

### CODE REVIEW

**Comment by luislobo** [comment]
@mikermcneil 
Also note, if you run ...

```bash
node ./node_modules/eslint/bin/eslint accessible bin errors lib --fix
```

... it wil automatically fix what can be fixed according to your .eslintrc config

**Comment by luislobo** [comment]
finally, that eslint version seems to NOT be compatible with 0.10 and 0.12, it uses `const`

**Comment by particlebanana** [comment]
@luislobo we added this line to the `scripts` in some of the adapters to handle the case of earlier versions of node:

```
"pretest": "nodever=`node -e \"console.log('\\`node -v\\`'[1]);\"` && if [ $nodever != \"0\" ]; then npm run lint; fi",
```

This was so we can still have Travis fail if the lint fails so that any PR's will fail for invalid syntax.

https://github.com/balderdashy/sails-postgresql/blob/bdf2b7d7e05b8a85cc0f79918d8add0c88a28298/package.json#L31-L34

**Comment by luislobo** [comment]
@particlebanana yeah, that works, the only drawback is that you don't have linting on older versions but anyway, in my opinion, those versions should not be supported anyway (although code might anyway be compatible with 0.1x)

**Pull request closed without merging**
