### PR TITLE
[proposal] Define a max limit varible

### PR DESCRIPTION
**Pull request by mazyvan**
Change that code in actionUtil file and create a maxLimit var in blueprints.js

### CODE REVIEW

**Comment by mikermcneil** [comment]
Hey @mazyvan, I think this is a good idea.

Would you have it prefer req.options.maxLimit if available, and camel-case the variable name (since it's not a constant-- I realize why you did it, because the other one is like this, but they really both ought to be camel cased).  e.g.

```js
// An optional ceiling for the `limit`.
// (if exceeded, limit will be set to maxLimit)
var maxLimit;
if (!_.isUndefined(req.options.maxLimit)) {
  maxLimit = req.options.maxLimit;
}
else if (!_.isUndefined(sails.config.blueprints.maxLimit) { 
  maxLimit = sails.config.blueprints.maxLimit;
}
```

Finally, would you also add a test, and include links to the places you're aware of in the docs where this would need to be added?

Thanks!

**Comment by mazyvan** [comment]
Hi @mikermcneil and thank you so much for check this. I did some changes to the code based on what you said. but unfortunately I don't know how to run a test. I mean I know it work haha, but I don't know how to use npm test or stuffs like that.

**Comment by mikermcneil** [comment]
@mazyvan Ok thanks!

@sgress454 so we'd have `maxLimit` in addition to `defaultLimit` (which i think makes sense, and would be straightforward enough to address. And I'd suppose we don't necessarily need to add this sort of a built-in boundary for any of the other criteria clauses....at least not yet.)


In Sails v1, a route pointed at a blueprint action might look something like:

```js
'GET /api/v4/products': {
  action: 'inventory/product/find',
  maxLimit: 100,
  defaultLimit: 25
}
```

or perhaps:

```js
'GET /api/v4/products': {
  controller: 'inventory/ProductController',
  action: 'find',
  maxLimit: 100,
  defaultLimit: 25
}
```

**Comment by sgress454** [comment]
Unfortunately this one timed out -- pretty much all of `actionUtil` has been replaced by `parseBlueprintOptions`.  We do have an example of [how to do `maxLimit` with `parseBlueprintOptions`](http://next.sailsjs.com/documentation/reference/configuration/sails-config-blueprints#?using-parseblueprintoptions), though.

**Comment by mazyvan** [comment]
Nice, thanks

**Pull request closed without merging**
