### PR TITLE
added support for cassandra as session store

### PR DESCRIPTION
**Pull request by angleto**
this code enable the possibility to use cassandra as session store, a pull request with templates modifications is going to be open on sails-generate-backend repository.

### CODE REVIEW

**Comment by tjwebb** [comment]
Awesome! @angleto can you include some tests?

**Comment by angleto** [comment]
@tjwebb sure I could add some test but I need a cassandra service running, I can set up an instance of  cassandra using travis, it is ok? Also, I do not see the service mongo and the tests for mongo session store in this repository, this test is just missing or it is on a different repo?

**Comment by mikermcneil** [comment]
@angleto that's right, we also need tests for the mongo session store. If you wouldn't mind setting those up on Travis CI, that'd be very helpful.

**Comment by mikermcneil** [comment]
@angleto Came back around to take a closer look at this, and it looks like you should be able to use https://github.com/B2MSolutions/connect-cassandra (a connect session adapter).  I'm working on docs for configuring custom session adapters in Sails today, so please let me know (open a new issue in [sails-docs](github.com/balderdashy/sails-docs)) if there are any special considerations to keep in mind here.  Thanks!

**Pull request closed without merging**
