### PR TITLE
[patch] Add adapter info to Issues template

### PR DESCRIPTION
**Pull request by luislobo**
What do you think about asking for adapter info and version?
Several times I see that being asked on issues, or that confusion happens because of things working for one adapter but not in an other one.
As always, my 2 cents.

### CODE REVIEW

**Comment by sgress454** [comment]
@luislobo I like this, but it requires more than just a change to the template, since we'd want this info to be optional.  Right now @sailsbot doesn't do "optional"...

**Comment by luislobo** [comment]
:+1: alright!

**Comment by sgress454** [comment]
@luislobo I like this -- let's modify slightly to:

```
**DB adapter name**: N/A
**DB adapter version**: N/A
```

@sailsbot doesn't do "optional", so we need the "N/A" placeholder for issues where the adapter is not important.

**Comment by luislobo** [comment]
@sgress454 done!

**Comment by luislobo** [comment]
@sgress454 Just a reminder so that you don't forget about this one

**Pull request merged**
