### PR TITLE
Update dependencies and solve problem on node 0.10 and iojs

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by listepo** [comment]
Fix test /home/travis/build/balderdashy/sails/test/integration/hook.cors_csrf.test.js for node 0.10(express 3.20.2)

**Comment by sgress454** [comment]
Hi @listepo can you go into a bit more detail as to what the issue is that this PR is solving?  It looks like you just updated all of the dependency versions, but it's not clear what the strategy was in doing so.

**Comment by listepo** [comment]
Most modules contain fixes minor bugs and improved performance

**Comment by listepo** [comment]
Upgrade express.js to 3.20.2 slove difference node 0.10 and 0.12 for hook.cors_csrf.test.js

**Comment by listepo** [comment]
Considered good form to do the updates and update modules in the project more

**Comment by listepo** [comment]
Solve problem sails.js on iojs see https://github.com/wadey/node-microtime/pull/25 and https://github.com/balderdashy/sails/pull/2771#issuecomment-88531136

**Comment by listepo** [comment]
Ping

**Comment by listepo** [comment]
Fix "npm WARN package.json Dependency 'colors' exists in both dependencies and devDependencies, using 'colors@~0.6.2' from dependencies" too

**Comment by listepo** [comment]
Ping

**Comment by sgress454** [comment]
Thanks for the reminder @listepo.  This took a little longer to get to b/c some of the dependencies were bumped considerably.  Our test coverage at this point is very good, but still not 100%, so I had to double-check some things manually (like handlebars support).  I also removed the Code Climate badge; if you think it's valuable you can open a separate PR for that so we can have a discussion around it and you can make your case.

**Comment by listepo** [comment]
@sgress454, thanks.

**Pull request merged**
