### PR TITLE
[Proposal] Handle untrusted bootstrap data in EJS

### PR DESCRIPTION
**Pull request by irlnathan**
# A Sails helper function to handle untrusted bootstrap data in EJS.

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: <%- sails.htmlInject('_csrf') %>,

    me: <%- sails.htmlInject('me') %>
  };
</script>
```

So I need to access `me` from inside of an inline `<script>` tag on an HTML page (e.g. for bootstrapping data). This would replace any custom _recursive_ HTML escaping I currently have to do on the injected value (e.g. `<%- stringifyAndHtmlEscape(me) %>`), as well as a `typeof val==='undefined' check`.

> I have the option of using the `<%= %> EJS tags`, which evaluates, escapes and injects anything between the tags or the `<%- %> EJS tags` which evaluates and injects anything between the tags as-is. I want to use `<%- %>` but then I’m responsible for protecting against potentially malicious data passed in `me`. 

## Proposed Solution

This...

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: <%- sails.htmlInject('_csrf') %>,

    me: <%- sails.htmlInject('me') %>
  };
</script>
```

...generates this:

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })('d8a831-d8a8381h1-adgadga3'),

    me: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })({
      gravatarUrl: '&lt;/script&gt;',
      admin: false
    })
  };
</script>
```

...and if `me` is not defined:

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })('d8a831-d8a8381h1-adgadga3'),

    me: undefined
  };
</script>
```

### CODE REVIEW

**Comment by particlebanana** [comment]
@irlnathan I'm posting your proposal here. Your PR overrides the entire Roadmap!

# A Sails helper function to handle untrusted bootstrap data in EJS.

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: <%- sails.htmlInject('_csrf') %>,

    me: <%- sails.htmlInject('me') %>
  };
</script>
```

So I need to access `me` from inside of an inline `<script>` tag on an HTML page (e.g. for bootstrapping data). This would replace any custom _recursive_ HTML escaping I currently have to do on the injected value (e.g. `<%- stringifyAndHtmlEscape(me) %>`), as well as a `typeof val==='undefined' check`.

> I have the option of using the `<%= %> EJS tags`, which evaluates, escapes and injects anything between the tags or the `<%- %> EJS tags` which evaluates and injects anything between the tags as-is. I want to use `<%- %>` but then I’m responsible for protecting against potentially malicious data passed in `me`. 

## Proposed Solution

This...

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: <%- sails.htmlInject('_csrf') %>,

    me: <%- sails.htmlInject('me') %>
  };
</script>
```

...generates this:

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })('d8a831-d8a8381h1-adgadga3'),

    me: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })({
      gravatarUrl: '&lt;/script&gt;',
      admin: false
    })
  };
</script>
```

...and if `me` is not defined:

```
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })('d8a831-d8a8381h1-adgadga3'),

    me: undefined
  };
</script>
```

**Comment by irlnathan** [comment]
@particlebanana thanks :)

**Comment by mikermcneil** [comment]
@irlnathan Thanks for putting this together.  This kind of utility is definitely much-needed and I think the biggest question is usage. Will add some more thoughts later today.  

And re: the PR: thanks @particlebanana.  Yeah I think the instructions for submitting proposals could still use some improvement-- right now you have to create the pull request first making some kind of edit to ROADMAP.md, then copy the link to the PR, then commit to that branch actually adding the link to the backlog. We could also set up a quick form for submitting proposals a la @mlynch's [approach for issue submissions](http://blog.ionic.io/how-ionic-uses-github-better/).

**Comment by mikermcneil** [comment]
So we should definitely set up a lower-level function as specced here, but perhaps it'd be a good idea to also go ahead and provide a simpler abstraction as well that's built on top of it, e.g.:
```ejs
<%- sails.exposeLocalsToBrowser() %>
```

Which would generate something like:
```html
<script type="text/javascript">
  window.SAILS_LOCALS = {
    _csrf: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })('d8a831-d8a8381h1-adgadga3'),

    me: (function (escapedValue){
      var unescaped = escapedValue;
      // Unescape all strings in `escapedValue`.
      // (recursively parse escapedValue if it is an array or dictionary)
      // (also need to prevent endless circular recursion for circular objects)
      return unescaped;
    })({
      gravatarUrl: '&lt;/script&gt;',
      admin: false
    })
  };
</script>
```


And perhaps with additional options for exposing a specific set of keys in locals, and to customize the namespace on the window global that's used:
```ejs
<%-
sails.exposeLocalsToBrowser({
  keys: ['_csrf', 'me'],
  namespace: 'SAILS_LOCALS'
})
%>
```


You could always use `sails.exposeLocalsToBrowser()` anywhere-- not just in a view.  It just returns a string containing HTML code (specifically a script tag).  A better name for the function might be in order -- if anyone reading this has feedback/ideas, please let me know!

**Comment by mikermcneil** [comment]
A very early pass at this is in place, see also test app here: https://github.com/mikermcneil/expose-locals-to-browser-xss-test-app

**Comment by mikermcneil** [comment]
Also published new patch version of rttc re: this (takes care of edge cases where the `constructor` property of nested objects has been overridden by some bratty little script)

**Comment by mikermcneil** [comment]
Ok, the usage of the view helper will now work in the most basic case as documented in this proposal.  That test app has a bunch of different cases, some of which pass and some of which fail, but the usage is definitely good to go and will not need to change:

```html
    <!--
      Bootstrap locals for access via client-side js
      ========================
    -->
    <%- exposeLocalsToBrowser() %>
    <script>
      // From here on out, we can access window.SAILS_LOCALS.
      console.log('Exposed locals to browser as `window.SAILS_LOCALS`.\n'+
        'Data:', window.SAILS_LOCALS);
    </script>
```
> _from https://github.com/mikermcneil/expose-locals-to-browser-xss-test-app/blob/c27f2b0f6aa45a3dd1dcae7206726a8d954014b2/views/layout.ejs#L68_


The options shown in the following examples are also supported:
+ `<%- exposeLocalsToBrowser({keys: [‘if specified’, ‘will only expose’, ‘this whitelist’,’of keys']}) %>`
+ `<%- exposeLocalsToBrowser({dontUnescapeOnClient: true}) %>`
+ `<%- exposeLocalsToBrowser({namespace: ’somethingBesidesSAILS_LOCALS_if_you_want'}) %>`


If anyone would like to take that for a test run or help add other XSS attack vectors, please do!  You'll just need to clone that repo and install or link the version of Sails on the master branch of GitHub as a dependency.  Keep in mind, not all of the test cases demonstrated in that app work yet.

**Comment by mikermcneil** [comment]
[Here's the link](https://github.com/mikermcneil/expose-locals-to-browser-xss-test-app/blob/356043178d5dd24f2e0ef911c1d89f97a681b007/config/routes.js#L66) to the spot in the code where I could use some help adding other attack vectors from the [OWASP cheat sheet](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet):  

https://github.com/mikermcneil/expose-locals-to-browser-xss-test-app/blob/356043178d5dd24f2e0ef911c1d89f97a681b007/config/routes.js#L66

**Comment by luislobo** [comment]
+1!

**Comment by mikermcneil** [comment]
Been looking at the latest developments with the `marked` vulnerability in relation to this.  I had to take a bit of a detour to educate myself on the details of the attack vectors with this kind of injection, and I'm just about confident enough to solve this properly. Still could use some help testing though! (specifically with the _unescaping_)

Resources.
+ Check out "Rule #3.1" here: https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#You_Need_a_Security_Encoding_Library
+ https://code.google.com/p/owasp-esapi-java/source/browse/trunk/src/main/java/org/owasp/esapi/codecs/JavaScriptCodec.java

**Comment by mikermcneil** [comment]
(also the ["XSS Prevention Rules Summary"](XSS_Prevention_Rules_Summary) on that OWASP page has a wonderful little reference table)

**Comment by mikermcneil** [comment]
This is fully implemented as of https://github.com/balderdashy/sails/commit/ae5e042c1640b4b39d5148fb38a0664028931920

**Comment by mikermcneil** [comment]
Here's an example of how to take advantage of `exposeLocalsToBrowser()` using Brushfire, the project from [Sails.js in Action](https://www.manning.com/books/sails-js-in-action):

https://github.com/sailsinaction/brushfire-ch15-end/pull/4

**Comment by mikermcneil** [comment]
XSS test app has also been updated accordingly: 
https://github.com/mikermcneil/expose-locals-to-browser-xss-test-app

**Comment by luislobo** [comment]
@mikermcneil This should be added to the list of stuff Sails handle, like, in the list of features, and also needs official documentation.

**Pull request merged**
