### PR TITLE
expose __n() in i18n hook

### PR DESCRIPTION
**Pull request by acis**
fix for #3488

### CODE REVIEW

**Comment by mikermcneil** [comment]
Hi @acis- I just restarted the build for this PR (our timeout was too slow for 0.10, wasn't your fault it was failing).

I'm down to help here if I can, and https://github.com/balderdashy/sails/issues/3488 is a good start towards communicating your use case, but I need to understand more about the problem; in particular how this is something that needs to change in the core i18n hook, and the purpose of the `__n` function.  

Since exposing a new function is a change in behavior/usage rather than a bug fix, this would need to be submitted [as a proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements).  Would you please review our updated contribution guide, then submit a proposal explaining your use case and how this approach would solve it?

Thanks!

**Comment by acis** [comment]
will do, thanks!

**Comment by mikermcneil** [comment]
@acis :+1:

**Comment by mikermcneil** [comment]
btw @acis - would you mind closing this PR and https://github.com/balderdashy/sails/issues/3488 in the mean time to help us keep organized?  Thank you!

**Pull request closed without merging**
