### PR TITLE
consolidate support channels in README

### PR DESCRIPTION
**Pull request by tjwebb**
- remove links to Trello and IRC, replace with Gitter
- deprecate google groups for community support, move to Github and SO
- minor style/grammar changes

### CODE REVIEW

**Comment by mikermcneil** [comment]
Looks great @tjwebb - I left a few minor notes inline

**Comment by tjwebb** [comment]
Thanks for the feedback

**Comment by CWyrtzen** [comment]
@mikermcneil @tjwebb is this ready?

**Comment by tjwebb** [comment]
I re-added the Google Groups link and merged in latest master. Ready to merge.

**Pull request merged**
