### PR TITLE
defaultLimit fix

### PR DESCRIPTION
**Pull request by swarthy**

### CODE REVIEW

**Comment by swarthy** [comment]
Need some help here :cold_sweat:

**Comment by masumeEbhami** [comment]
what is problem ?

**Comment by swarthy** [comment]
Can't find how changes broke tests

**Comment by masumeEbhami** [comment]
are you have
var _ = require('lodash'),
  mergeDefaults = require('merge-defaults'),
  util = require('util');

**Comment by masumeEbhami** [comment]
i use last version and this work for me

**Comment by masumeEbhami** [comment]
swarthy 
your problem has fixed?

**Comment by swarthy** [comment]
Yes, thanks a lot!

**Comment by tjwebb** [comment]
@masumeEbhami @swarthy thanks guys for helping figure this out

**Pull request closed without merging**
