### PR TITLE
[feature] Add configuration to csrf to be able to change default /csrfTo...

### PR DESCRIPTION
**Pull request by konstantinzolotarev**
...ken route #2366

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Looks good to me. What do you think @mikermcneil @sgress454 ?

**Comment by mikermcneil** [comment]
@konstantinzolotarev @loicsaintroch  thanks!  Looks like it needs a rebase (but also travis is being crazy) If travis calms down (tests pass + merge can be performed automatically), can merge this afternoon

**Comment by mikermcneil** [comment]
@konstantinzolotarev please see https://github.com/balderdashy/sails/pull/2367#commitcomment-9484371 -- this refactor introduces potential entanglement issues

**Comment by konstantinzolotarev** [comment]
@mikermcneil Sorry for long response. Was in a trip. 
Fixed.

**Comment by loicsaintroch** [comment]
Looks good to me. Ok to merge this feature @mikermcneil @sgress454 ?

**Comment by CWyrtzen** [comment]
Bump~

**Comment by mikermcneil** [comment]
@konstantinzolotarev thanks!  If you wouldn't mind rebasing so we can auto-merge, we can go ahead and do that.

**Comment by konstantinzolotarev** [comment]
@mikermcneil done

**Comment by loicsaintroch** [comment]
Thank you very much for your contribution @konstantinzolotarev, we appreciate your support.

**Pull request merged**
