### PR TITLE
Enable `sails deploy`: Deploy Sails Apps within Minutes

### PR DESCRIPTION
**Pull request by felixrieseberg**
A Pull Request with :heart: from Microsoft! Crazy, I know. But hear me out: About a week ago, @mikermcneil, @sedouard and myself talked about how cool it would be if you could just run a command like `sails deploy` and sails would automatically create and deploy a website with the current sails app. We got some pizza and built that thing (Thanks to Mike for coming up to San Fran).

**TL;DR Version**
Run `sails deploy` and watch sails create an Azure Website and deploy your app. You might not have an Azure account - the script does some basic guidance to help you set one up, but this is really cool once you already have one. 

**Costs**
Azure has free accounts & up to ten free websites per account. The created websites are automatically set to be free. Nothing speaks against using the existing code to implement other providers.

**Full Feature List**
We first built `machinepack-azure`, which is capable of registering and setting up your Azure account, as well as creating a website, uploading files, uploading bash or powershell scripts, exposing said scripts via REST, calling saids scripts. Combined, it gives us the power to do pretty much anything.

The logical flow is as follows:
1) Check if an Azure account is setup and registered in the current `env`
2) Check if a website with the given name already exists in the current account
3) If not, one is created
4) The sails app is zipped up
5) The zip package is uploaded to the created website
6) A cleanup/unpack/install script is uploaded and registered and exposed
7) The script is called and the output piped through to the local console

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Thank you for your awesome contribution @felixrieseberg. Love it. We were waiting for a deployment solution for a long time now. Glad to see Microsoft contributing in Sails and open-source projects generally. Thank you.

**Comment by mikermcneil** [comment]
@loicsaintroch @felixrieseberg

**Comment by brooklynDev** [comment]
Very cool! Out of curiosity though, are there plans in the future to extend this beyond Azure? Something like `sails deploy azure` or `sails deploy heroku`. Without that, it feels kind of odd that `sails` is married to Azure.

**Comment by felixrieseberg** [comment]
@brooklynDev I made sure to write code that totally allows that.

**Comment by tarlepp** [comment]
This is really nice addition and I'm totally waiting for deploy commands for another platforms like @brooklynDev points out.

It would be really nice to have some guidelines how to make your own platform implementations for this command. Eg I work in IT company that uses it's own structure for applications, and I bet that we would write our own deploy command like ```sails deploy ptcs [vm here]``` 

So my next question is: When do you guys think that we can start building something like this? Basically we need some guidelines and examples for this.

**Comment by tikotzky** [comment]
@tarlepp have you seen PR #2667 from @brooklynDev?

That gives you the ability to add custom commands to sails via an npm module.

Perhaps the azure implementation should be changed to work like that instead of being baked into sails.

**Comment by tarlepp** [comment]
@tikotzky just checked that #2667, and it seems really nice. Now we need to make this deploy hook to be easily extended (if it's not yet) and build supports for multiple platforms.

This seems to be very interesting and promising hook!

**Comment by mikermcneil** [comment]
more info here https://github.com/balderdashy/sails/pull/2667#issuecomment-75474760

**Comment by alterx** [comment]
@mikermcneil any chances this gets merged into master soon?

**Comment by felixrieseberg** [comment]
@alterx: We're currently working on a slightly cleaner version with custom commands. But yes, this will eventually become part of Sails.

**Comment by alterx** [comment]
Awesome @felixrieseberg this the exact thing I need for a project I'm working on. 
Looking forward this to happen

**Comment by mikermcneil** [comment]
Hey everyone, I compiled the spec work so far [here](http://michaelmcneil.com/post/114677471702/spec-for-custom-commands-deployment-strategies).  This is something I'm personally really excited about.  @sgress454 will have more to report soon.

cc @alterx @felixrieseberg @tikotzky @tarlepp @brooklynDev @loicsaintroch @seoduard

**Comment by sgress454** [comment]
Happy to say that `sails deploy` is fully integrated into the CLI, and the first deploy module ([sails-deploy-azure](https://github.com/mikermcneil/sails-deploy-azure)) has been published.  Huge thanks to @felixrieseberg for his work on both.  Looking forward to seeing other deploy modules created for the framework!

We will push out a patch release of Sails very soon so that everyone can take advantage of the new deploy feature.  Closing this PR since it ended up being separated into [sails-deploy-azure](https://github.com/mikermcneil/sails-deploy-azure).

**Comment by felixrieseberg** [comment]
🎉🎉🎉

**Pull request closed without merging**
