### PR TITLE
Added '--coffee' generator option + ability to set generation language in configs

### PR DESCRIPTION
**Pull request by t3chnoboy**
Added:
- ability to generate models, controllers and adapters in CoffeeScript (Requested feature #715, #350, #478)
- separate templates for CoffeeScript
- ability to set controllers and adapters generation language in configs

**Examples:** 
`sails generate model User --coffee`
generates: [User.coffee](https://gist.github.com/t3chnoboy/7512688)
`sails generate model User name:string password:string email:email age:number --coffee`
generates: [User.coffee](https://gist.github.com/t3chnoboy/7512645)
`sails generate controller User --coffee`
generates: [UserController.coffee](https://gist.github.com/t3chnoboy/7512718)
`sails generate controller User comment like create --coffee`
generates: [UserController.coffee](https://gist.github.com/t3chnoboy/7512751)

_note:_ Indent looks broken in some gists. Probably a gist or vim-gist plugin issue. Generated files are properly indented.
scrot

You can also set default generation language for controllers in config/controllers.js.

**Example:**
In new sails project `sails generate controller User` will generate User.js.
But if you add `language: 'coffee'` to config/controllers.js
`sails generate controller User` will generate [UserController.coffee](https://gist.github.com/t3chnoboy/7512718)
Removing `language: 'coffee'` or setting it to `language: 'js'` in config/controllers.js will restore default behavior.
For example `sails generate controller User`will generate UserController.js written in JavaScript.

_note:_ You can't set default generation language for models because there is no config for models in config/

### CODE REVIEW

**Comment by Kikobeats** [comment]
@t3chnoboy @mikermcneil 

I checked that this works fine at this moment, but I have a one question: what about generate coffee files under `sails new app --coffee` ?

**Comment by wancharle** [comment]
there is support for generate services too with --coffee?

**Comment by korneel** [comment]
@Kikobeats :+1:

**Comment by unclebanana** [comment]
@Kikobeats +1

**Pull request closed without merging**
