### PR TITLE
Added LiveScript support

### PR DESCRIPTION
**Pull request by borestad**
Hi.

I added support for LiveScript. Even though #2122 seems like a better solution in the long run, it solves my needs. I didn't add support for scaffolding.

Is this something that you may find interesting to merge?

### CODE REVIEW

**Comment by loicsaintroch** [comment]
I am ok with that. What do you think @tjwebb ?

**Comment by tjwebb** [comment]
Looks good to me, thanks @loicsaintroch

**Comment by internalfx** [comment]
OK...I'm annoyed now..

I put together a pull request #2599 that added support for:

- CoffeeScript
- IcedCoffeeScript
- made future languages easier to add
- and lazily loaded the modules for said languages....

It's been rotting in the queue for months and somehow this got merged?!?!

I'm not saying this is bad code, but I feel like someone cut the line!

If my PR is bad tell me what to fix, but I feel a little cheated here.

@borestad please dont be offended, nothing against you. But I think your job may have been easier had they merged mine first...

**Comment by tjwebb** [comment]
@internalfx hey man, sorry about that. We've been going through Pull Requests and trying to catch up with merging in useful things. But I think we've been going in the wrong order. I see your point. I'd be annoyed too. 

If you don't mind merging latest into your PR so we can merge without conflicts, I'll make a point to review your PR next and merge it. Thanks.

**Comment by internalfx** [comment]
@tjwebb Happy to do it....and thanks

I'm reworking my PR to also include LiveScript support..so everyone wins!

**Comment by tjwebb** [comment]
Thanks, and I apologize again for our oversight.

We're in the process of re-organizing the core team so that we can start moving forward at a more rapid pace, and so we can be more responsive to these kinds of issues. Are you interested in being involved in this process?

**Comment by internalfx** [comment]
Sure. I use sails for pretty much everything now...

I just updated from master and added livescript support to #2599

continue conversation at #2599?

**Pull request merged**
