### PR TITLE
Removes the socket hook's dependency upon the session hook.

### PR DESCRIPTION
**Pull request by lwansbrough**
So this removes the session hook requirements from the sockets hook. Helpful for those of us using JWTs.

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Any update on this pull request guys?

**Comment by mikermcneil** [comment]
@loicsaintroch @lwansbrough I think this is sorted in https://github.com/balderdashy/sails-hook-sockets/blob/master/lib/initialize.js#L50 - would you mind installing 0.11.0-rc5 and giving it a go?

**Comment by lwansbrough** [comment]
Thanks Mike, I'll take a look a little later.

**Comment by mikermcneil** [comment]
@lwansbrough alright I believe we're good now.  Added tests here: https://github.com/balderdashy/sails-hook-sockets/blob/master/test/without-session.test.js  Going to go ahead and close- thanks for your help :)

**Comment by lwansbrough** [comment]
@mikermcneil Oops forgot to report back! Works great thank you.

**Comment by fabdrol** [comment]
@mikermcneil Does this require 0.11?

**Comment by tarlepp** [comment]
@fabdrol yep it requires 0.11.x sails, I just tested this with sails 0.11.0 and session hook disabled and it works like a charm.

**Pull request closed without merging**
