### PR TITLE
update blueprint: prevent updating PK, but leave it for Model lifecycle callbacks

### PR DESCRIPTION
**Pull request by jakutis**
might crash your connection provider. tested only on sails-mongo.

### CODE REVIEW

**Comment by sgress454** [comment]
Can you put the warning about not changing the primary key back in?

**Comment by jakutis** [comment]
Yes, again misunderstood which warning was wanted. Restored.

**Comment by sgress454** [comment]
I meant the console warning--it's cool, I took care of it.  Thanks for your help!

**Comment by jakutis** [comment]
oooh.. ok.

Thank you for making Sails!

**Pull request merged**
